<a href="https://colab.research.google.com/github/tomcat472/2023_python/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Introduction to Tensorflow**

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

### **create scalar**

In [3]:
scalar=tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


### **create vector**

In [4]:
vector=tf.constant([10,7])
print(vector)
print(vector.ndim)

tf.Tensor([10  7], shape=(2,), dtype=int32)
1


### **create matrix**

In [5]:
matrix=tf.constant([[10,7],[7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


### **create another matrix**

In [6]:
another_matrix=tf.constant([[10,7],
                            [3,2]],dtype=tf.float16)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 3.  2.]], shape=(2, 2), dtype=float16)
2


### **create a tensor**

In [7]:
tensor=tf.constant([[[1,2,3],[4,5,6]]],dtype=tf.int32)
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)
3


### Changeable tensor and  unchangeable tensor

In [8]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [9]:
# changeable_tensor[0]=19
# unchangeable_tensor[0]=19
# changeable_tensor, unchangeable_tensor

In [10]:
# tensorflow မှာ value update လုပ်မယ်ဆိုရင် assign ကို သုံးပေးရပါတယ်။
# variable နဲ့ ပြုလုပ်ထားတဲ့ tensor မှာပဲ သုံးလို့ရတာ ဖြစ်ပါတယ်။
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### **creating random tensor**

In [11]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
print(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [12]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
print(random_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [13]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### **Shuffle order or elements in a tensor**

In [14]:
A=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [15]:
tf.random.shuffle(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [16]:
# shuffle လုပ်တိုင်း ထွက်လာတဲ့ output တူညီချင်ရင် seed သတ်မှတ်ပေးရပါတယ်။
# seed မှာလဲ ၂ မျိုးရှိပါတယ်။ global level random seed နဲ့
# operation level random seed တို့ဖြစ်ပါတယ်။
tf.random.shuffle(A,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [17]:
tf.random.shuffle(A,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [18]:
tf.random.set_seed(42)
tf.random.shuffle(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [19]:
tf.random.set_seed(42)
tf.random.shuffle(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

### **Creation tensors of zeros and ones**

In [20]:
tf.ones([3,4],dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [21]:
tf.zeros(shape=(3,4),dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

### **Create tensor from numpy array**

In [22]:
# The main difference between numpy arrays and tensor is that tensor
#  can be run on a GPU computing.
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [23]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### **Getting information from tensors**

In [24]:
X=tf.zeros(shape=[2,3,4,5])
X

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
# data types of every elements
print(X.dtype)

# number of dimension (rank)
print(X.ndim)

# shape of tensor
print(X.shape)

# elements along the 0 axis
print(X.shape[0])

# elements along the last axis
print(X.shape[-1])

# total number of elements in our tensor
print(tf.size(X).numpy())

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
120


**Indexing tensors**

In [26]:
X

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

### get the first 2 elements of each dimensions

In [27]:
X[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# get the first element from each dimension from each
# index except for the final one
X[:1,:1,:1,:5]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
# create a rank 2 tensor (2 dimesions)
B=tf.constant([[10,7],[3,4]])
print(B.shape)
print(B.ndim)

(2, 2)
2


In [30]:
# get the last item of each of row of our rank 2 tensor
# B[row,column]
B[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [31]:
B[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>

In [32]:
B[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

### **add in extra dimension to rank 2 tensor**

In [33]:
C=B[...,tf.newaxis]
C

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
# alternative to tf.newaxis
tf.expand_dims(C,axis=-1)
# -1 mean expand the final axis

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 3]],

        [[ 4]]]], dtype=int32)>

### **Basic Opearations**

In [35]:
Z=tf.constant([[1,2],[3,4]])
Z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [36]:
Z+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [37]:
Z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [38]:
Z*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [39]:
tf.multiply(Z,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [40]:
tf.subtract(Z,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

### **Matrix multiplication in tensorflow**

In [41]:
# In machine learning, matrix multiplication is one of the most common
# tensor operations.
A=tf.constant([[1,2],[3,4]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [42]:
tf.matmul(A,A)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [43]:
 A @ A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [44]:
N=tf.constant([[1,2,3],[4,5,6]]) #2x3
M=tf.constant([[2,4],[5,8],[10,9]]) #3x2
print(N)
print(M)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2  4]
 [ 5  8]
 [10  9]], shape=(3, 2), dtype=int32)


In [45]:
tf.matmul(N,M)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 42,  47],
       [ 93, 110]], dtype=int32)>

In [46]:
N @ M

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 42,  47],
       [ 93, 110]], dtype=int32)>

### ***Changing the shape of tensor***

In [47]:
N

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [48]:
tf.reshape(N,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [49]:
N @ tf.reshape(N,shape=(3,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [50]:
tf.matmul(tf.reshape(N,shape=(3,2)),N)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [51]:
# transposing the tensor
tf.transpose(N)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [52]:
tf.matmul(tf.transpose(N),N)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

### matrix multiplication is also referred to as the dot product
* tf.matmul()
* tf.tensordot()
* @

In [53]:
tf.matmul(tf.transpose(N),N)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

In [54]:
tf.transpose(N) @ N

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

In [55]:
tf.tensordot(tf.transpose(N),N,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>