<a href="https://colab.research.google.com/github/tomcat472/tomcat_deep_learning_with_TensorFlow/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Introduction to Tensorflow**

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

### **create scalar**

In [3]:
scalar=tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


### **create vector**

In [4]:
vector=tf.constant([10,7])
print(vector)
print(vector.ndim)

tf.Tensor([10  7], shape=(2,), dtype=int32)
1


### **create matrix**

In [5]:
matrix=tf.constant([[10,7],[7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


### **create another matrix**

In [6]:
another_matrix=tf.constant([[10,7],
                            [3,2]],dtype=tf.float16)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 3.  2.]], shape=(2, 2), dtype=float16)
2


### **create a tensor**

In [7]:
tensor=tf.constant([[[1,2,3],[4,5,6]]],dtype=tf.int32)
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)
3


### Changeable tensor and  unchangeable tensor

In [8]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [9]:
# changeable_tensor[0]=19
# unchangeable_tensor[0]=19
# changeable_tensor, unchangeable_tensor

In [10]:
# tensorflow မှာ value update လုပ်မယ်ဆိုရင် assign ကို သုံးပေးရပါတယ်။
# variable နဲ့ ပြုလုပ်ထားတဲ့ tensor မှာပဲ သုံးလို့ရတာ ဖြစ်ပါတယ်။
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### **creating random tensor**

In [11]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
print(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [12]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
print(random_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [13]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### **Shuffle order or elements in a tensor**

In [14]:
A=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [15]:
tf.random.shuffle(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [16]:
# shuffle လုပ်တိုင်း ထွက်လာတဲ့ output တူညီချင်ရင် seed သတ်မှတ်ပေးရပါတယ်။
# seed မှာလဲ ၂ မျိုးရှိပါတယ်။ global level random seed နဲ့
# operation level random seed တို့ဖြစ်ပါတယ်။
tf.random.shuffle(A,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [17]:
tf.random.shuffle(A,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [18]:
tf.random.set_seed(42)
tf.random.shuffle(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [19]:
tf.random.set_seed(42)
tf.random.shuffle(A)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

### **Creation tensors of zeros and ones**

In [20]:
tf.ones([3,4],dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [21]:
tf.zeros(shape=(3,4),dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

### **Create tensor from numpy array**

In [22]:
# The main difference between numpy arrays and tensor is that tensor
#  can be run on a GPU computing.
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [23]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### **Getting information from tensors**

In [24]:
X=tf.zeros(shape=[2,3,4,5])
X

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
# data types of every elements
print(X.dtype)

# number of dimension (rank)
print(X.ndim)

# shape of tensor
print(X.shape)

# elements along the 0 axis
print(X.shape[0])

# elements along the last axis
print(X.shape[-1])

# total number of elements in our tensor
print(tf.size(X).numpy())

<dtype: 'float32'>
4
(2, 3, 4, 5)
2
5
120


**Indexing tensors**

In [26]:
X

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

### get the first 2 elements of each dimensions

In [27]:
X[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
# get the first element from each dimension from each
# index except for the final one
X[:1,:1,:1,:5]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
# create a rank 2 tensor (2 dimesions)
B=tf.constant([[10,7],[3,4]])
print(B.shape)
print(B.ndim)

(2, 2)
2


In [30]:
# get the last item of each of row of our rank 2 tensor
# B[row,column]
B[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [31]:
B[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3], dtype=int32)>

In [32]:
B[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

### **add in extra dimension to rank 2 tensor**

In [33]:
C=B[...,tf.newaxis]
C

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
# alternative to tf.newaxis
tf.expand_dims(C,axis=-1)
# -1 mean expand the final axis

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 3]],

        [[ 4]]]], dtype=int32)>

### **Basic Opearations**

In [35]:
Z=tf.constant([[1,2],[3,4]])
Z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [36]:
Z+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [37]:
Z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [38]:
Z*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [39]:
tf.multiply(Z,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [40]:
tf.subtract(Z,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

### **Matrix multiplication in tensorflow**

In [41]:
# In machine learning, matrix multiplication is one of the most common
# tensor operations.
A=tf.constant([[1,2],[3,4]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [42]:
tf.matmul(A,A)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [43]:
 A @ A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [44]:
N=tf.constant([[1,2,3],[4,5,6]]) #2x3
M=tf.constant([[2,4],[5,8],[10,9]]) #3x2
print(N)
print(M)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2  4]
 [ 5  8]
 [10  9]], shape=(3, 2), dtype=int32)


In [45]:
tf.matmul(N,M)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 42,  47],
       [ 93, 110]], dtype=int32)>

In [46]:
N @ M

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 42,  47],
       [ 93, 110]], dtype=int32)>

### ***Changing the shape of tensor***

In [47]:
N

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [48]:
tf.reshape(N,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [49]:
N @ tf.reshape(N,shape=(3,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [50]:
tf.matmul(tf.reshape(N,shape=(3,2)),N)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [51]:
# transposing the tensor
tf.transpose(N)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [52]:
tf.matmul(tf.transpose(N),N)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

### matrix multiplication is also referred to as the dot product
* tf.matmul()
* tf.tensordot()
* @

In [53]:
tf.matmul(tf.transpose(N),N)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

In [54]:
tf.transpose(N) @ N

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

In [55]:
tf.tensordot(tf.transpose(N),N,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]], dtype=int32)>

### **Change Data Types**

In [56]:
A_1=tf.constant([1.2,1.3])
print(A_1.dtype)

<dtype: 'float32'>


In [57]:
A_2=tf.constant([23,2])
print(A_2.dtype)

<dtype: 'int32'>


In [58]:
# changing from flaot32 to float16 (reduced precision)
B=tf.cast(A_1,dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 1.3], dtype=float16)>

In [59]:
# changing from int32 to float32
C=tf.cast(A_2,dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([23.,  2.], dtype=float32)>

### **Tensor Aggregation**

In [60]:
# aggregating tensors is that condensing them from multiple values
# down to a smaller amount of value.

In [61]:
# absolute values
D=tf.constant([-123,-3.4])
D

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-123. ,   -3.4], dtype=float32)>

In [62]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([123. ,   3.4], dtype=float32)>

In [63]:
# create a random tensor with valus between 0 and 100 of size 50
import numpy as np
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([18, 61, 75, 56, 45, 21, 82, 32, 87, 43, 51, 56, 91, 64, 19, 78, 51,
       58, 81,  5, 46, 51,  3, 74, 79, 45, 73, 87, 12, 95, 25, 14, 59, 25,
       25, 99, 83, 83, 88, 23,  5, 38, 67, 56, 96, 72, 88, 45, 95, 88])>

In [64]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [65]:
# finding the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [66]:
np.min(E)

3

In [67]:
# Finding the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [68]:
np.max(E)

99

In [69]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [70]:
np.mean(E)

56.26

In [71]:
# find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2813>

In [72]:
np.sum(E)

2813

In [73]:
# to find variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=785>

In [74]:
np.var(E)

785.1924000000002

In [75]:
# to find standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.021282>

In [76]:
np.std(E)

28.021284767119447

### **Findint the positional maximum and minimum**

In [77]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [78]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [79]:
F[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [80]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [81]:
# Find the max values of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [82]:
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [83]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [84]:
# find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### **Squeezing a tensor (removing all single dimensions)**

In [85]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[5]),shape=(1,1,1,1,5))
G

<tf.Tensor: shape=(1, 1, 1, 1, 5), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041]]]]],
      dtype=float32)>

In [86]:
G.shape

TensorShape([1, 1, 1, 1, 5])

In [87]:
G_squeezed=tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(5,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
       dtype=float32)>,
 TensorShape([5]))

### **One-hot encoding tensors**

In [88]:
A=[0,1,2,3]
# one hot encode our list of indices
tf.one_hot(A,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [89]:
# specify custom values for one hot encoding
tf.one_hot(A,depth=4,on_value='tomcat',off_value='sv')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'tomcat', b'sv', b'sv', b'sv'],
       [b'sv', b'tomcat', b'sv', b'sv'],
       [b'sv', b'sv', b'tomcat', b'sv'],
       [b'sv', b'sv', b'sv', b'tomcat']], dtype=object)>

### **Squaring, log, square root**

In [90]:
J=tf.range(0,10)
J

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [91]:
# square
tf.square(J)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [92]:
# squareroot
tf.sqrt(tf.cast(J,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.2360678,
       2.4494896, 2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [93]:
# log
tf.math.log(tf.cast(J,dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### **Tensorflow and Numpy**

In [94]:
# create a tensor directly from a Numpy array
K=tf.constant(np.array([2,3,4,3,4]))
K

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 3, 4, 3, 4])>

In [95]:
# convert tensor back to numpy array
np.array(K), type(np.array(K))

(array([2, 3, 4, 3, 4]), numpy.ndarray)

In [96]:
# convert tensor to numpy array
K.numpy, type(K.numpy)

(<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 3, 4, 3, 4])>>,
 method)

In [97]:
# default types of each are slightly different
numpy_P=tf.constant(np.array([2,3,4,4]))
tensor_P=tf.constant([2,3,4,3])
numpy_P.dtype, tensor_P.dtype

(tf.int64, tf.int32)

In [98]:
numpy_P=tf.constant(np.array([2.,3.,4.,4.]))
tensor_P=tf.constant([2.,3.,4.,3.])
numpy_P.dtype, tensor_P.dtype

(tf.float64, tf.float32)

### **Finding access to GPUs**

In [99]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [100]:
# run time type ပြောင်းပြီးမှ စမ်းပါ။
!nvidia-smi

Fri Oct 20 04:18:55 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0    30W /  70W |    361MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------