<a href="https://colab.research.google.com/github/tomcat472/2023_python/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensorflow

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

In [3]:
# create scalar
scalar=tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [4]:
# create vector
vector=tf.constant([10,7])
print(vector)
print(vector.ndim)

tf.Tensor([10  7], shape=(2,), dtype=int32)
1


In [5]:
# create matrix
matrix=tf.constant([[10,7],[7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


In [6]:
# create another matrix
another_matrix=tf.constant([[10,7],
                            [3,2]],dtype=tf.float16)
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 3.  2.]], shape=(2, 2), dtype=float16)
2


In [7]:
# create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]]],dtype=tf.int32)
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)
3


### Changeable tensor and  unchangeable tensor

In [8]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [9]:
# changeable_tensor[0]=19
# unchangeable_tensor[0]=19
# changeable_tensor, unchangeable_tensor

In [10]:
# tensorflow မှာ value update လုပ်မယ်ဆိုရင် assign ကို သုံးပေးရပါတယ်။
# variable နဲ့ ပြုလုပ်ထားတဲ့ tensor မှာပဲ သုံးလို့ရတာ ဖြစ်ပါတယ်။
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [11]:
# creating random tensor
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
print(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [12]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
print(random_2)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [13]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>